import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MyAppIcon{
  static const IconData editt = Icons.edit_outlined;
  static const IconData favorite = Icons.favorite_rounded;
  static const IconData outlinedfav = Icons.favorite_outline_rounded;
  static const IconData star = Icons.star;
  static const IconData camera =Icons.add_a_photo_outlined;
  static const IconData mic = Icons.mic;
  static const IconData searchh = Icons.search;
  static const IconData bed = Icons.bed;
  static const IconData chair = Icons.chair_alt_outlined;
  static const IconData sofas = Icons.chair_outlined;
  static const IconData table = Icons.table_restaurant_outlined;
  static const IconData back = Icons.arrow_back_ios_new_outlined;
  static const IconData cart = Icons.shopping_cart_outlined;
  static const IconData close = Icons.close;
  static const IconData backop = Icons.arrow_forward_ios;
  static const IconData box = Icons.card_travel_outlined;
  static const IconData truck = Icons.fire_truck_outlined;
  static const IconData reviews = Icons.content_paste_search_outlined;
  static const IconData profilecircle = Icons.account_circle_outlined;
  static const IconData settings = Icons.settings_outlined;
  static const IconData headphone = Icons.headphones_outlined;
  static const IconData returnn = Icons.screen_search_desktop_outlined;
  static const IconData more = Icons.more_horiz;
  static const IconData receipt = Icons.receipt_long_outlined;
  static const IconData ques = Icons.question_mark_outlined;
  static const IconData category = Icons.category_outlined;
  static const IconData home = Icons.home_outlined;
  static const IconData notification = Icons.notifications_outlined;
  static const IconData outlinedstar = Icons.star_border_outlined;
  static const IconData lock = Icons.lock_outline;
  static const IconData passwordshow = Icons.remove_red_eye;
  static const IconData passordclose = Icons.visibility_off_outlined;
  static const IconData share = Icons.share_outlined;
  static const IconData bag = Icons.shopping_bag_outlined;
  static const IconData work = Icons.work_outline_outlined;
}